# Generated by Django 4.2.30 on 2026-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(help_text='Name of this certificate profile (cn)', max_length=255, unique=True, verbose_name='Profile Name')),
                ('description', models.TextField(blank=True, help_text='Description of what this profile is used for')),
                ('template_cn', models.CharField(help_text='Name of the certificate template to use', max_length=255, verbose_name='Template Name')),
                ('hostname_patterns', models.JSONField(default=list, help_text='List of hostnames or patterns (wildcards supported)', verbose_name='Hostname Patterns')),
                ('require_kerberos_auth', models.BooleanField(default=True, help_text='If true, requires Kerberos authentication via ACME', verbose_name='Require Kerberos Auth')),
                ('allowed_principals', models.JSONField(blank=True, default=list, help_text='List of specific Kerberos principals allowed (empty = all)', verbose_name='Allowed Principals')),
                ('auto_renewal_days', models.PositiveIntegerField(default=30, help_text='Days before expiration to trigger renewal notification', verbose_name='Auto-renewal Window')),
                ('enabled', models.BooleanField(default=True, help_text='If false, this profile will not be used by ACME', verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Certificate Profile',
                'verbose_name_plural': 'Certificate Profiles',
                'db_table': 'ldap_certificate_profiles',
            },
        ),
        migrations.CreateModel(
            name='CertificateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(help_text='Common Name from certificate subject (cn)', max_length=255, verbose_name='Subject CN')),
                ('serial_number', models.CharField(help_text='Certificate serial number (hex format)', max_length=64, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='valid', help_text='Current certificate status', max_length=20, verbose_name='Status')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the certificate was revoked', null=True, verbose_name='Revoked At')),
                ('not_before', models.DateTimeField(verbose_name='Not Before')),
                ('not_after', models.DateTimeField(verbose_name='Not After')),
                ('issuer_cn', models.CharField(help_text='Common Name of the issuing CA', max_length=255, verbose_name='Issuer CN')),
                ('profile_cn', models.CharField(blank=True, help_text='Name of the certificate profile used', max_length=255, verbose_name='Profile Name')),
                ('template_cn', models.CharField(blank=True, help_text='Name of the certificate template used', max_length=255, verbose_name='Template Name')),
                ('auth_principal', models.CharField(blank=True, help_text='Kerberos principal that authorized this certificate request', max_length=255, verbose_name='Authorization Principal')),
                ('revocation_reason', models.CharField(blank=True, help_text='Reason for certificate revocation', max_length=50, verbose_name='Revocation Reason')),
                ('storage_path', models.CharField(blank=True, help_text='Path to where the certificate is stored (external)', max_length=512, verbose_name='Certificate Path')),
                ('private_key_path', models.CharField(blank=True, help_text='Path to where the private key is stored (external)', max_length=512, verbose_name='Private Key Path')),
                ('acme_order_id', models.CharField(blank=True, help_text='ID of the ACME order that issued this certificate', max_length=255, verbose_name='ACME Order ID')),
            ],
            options={
                'verbose_name': 'Certificate Record',
                'verbose_name_plural': 'Certificate Records',
                'db_table': 'ldap_certificate_records',
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(help_text='Name of this certificate template (cn)', max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, help_text='Description of what this template is used for')),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='Certificate validity period in days', verbose_name='Validity (days)')),
                ('key_size', models.PositiveIntegerField(choices=[(1024, '1024 bits'), (2048, '2048 bits'), (3072, '3072 bits'), (4096, '4096 bits')], default=2048, help_text='Size of the RSA key to generate', verbose_name='RSA Key Size')),
                ('usage_key_cert_sign', models.BooleanField(default=False, help_text='If true, certificate can sign other certificates', verbose_name='Key Certificate Sign')),
                ('usage_crl_sign', models.BooleanField(default=False, help_text='If true, certificate can sign CRLs', verbose_name='Key CRL Sign')),
                ('usage_key_encipherment', models.BooleanField(default=True, help_text='If true, key can be used for encipherment', verbose_name='Key Encipherment')),
                ('usage_key_data_sign', models.BooleanField(default=False, help_text='If true, key can be used for digital signatures', verbose_name='Key Data Signature')),
                ('usage_server_auth', models.BooleanField(default=False, help_text='If true, certificate can be used for TLS server auth', verbose_name='Server Authentication')),
                ('usage_client_auth', models.BooleanField(default=False, help_text='If true, certificate can be used for TLS client auth', verbose_name='Client Authentication')),
                ('usage_code_signing', models.BooleanField(default=False, help_text='If true, certificate can be used for code signing', verbose_name='Code Signing')),
                ('usage_email_protection', models.BooleanField(default=False, help_text='If true, certificate can be used for email protection', verbose_name='Email Protection')),
                ('san_dns_pattern', models.CharField(blank=True, help_text="Pattern for DNS SANs (e.g., '*.example.com' or specific names)", max_length=255, verbose_name='SAN DNS Pattern')),
                ('san_ip_pattern', models.CharField(blank=True, help_text='Pattern for IP address SANs', max_length=255, verbose_name='SAN IP Pattern')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this template will be used as default when no match is found', verbose_name='Is Default Template')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'db_table': 'ldap_certificate_templates',
            },
        ),
    ]
